let court = [
  {character: 'Duke', image: 'https://vectr.com/alexamoy/a2E8Y4Jxom.png?width=640&height=640&select=a2E8Y4Jxompage0'},{character: 'Duke', image: 'https://vectr.com/alexamoy/a2E8Y4Jxom.png?width=640&height=640&select=a2E8Y4Jxompage0'},{character: 'Duke', image: 'https://vectr.com/alexamoy/a2E8Y4Jxom.png?width=640&height=640&select=a2E8Y4Jxompage0'},
  {character: 'Assassin', image: 'https://vectr.com/alexamoy/g4KIDpKNz.png?width=640&height=640&select=g4KIDpKNzpage0'},{character: 'Assassin', image: 'https://vectr.com/alexamoy/g4KIDpKNz.png?width=640&height=640&select=g4KIDpKNzpage0'}, {character: 'Assassin', image: 'https://vectr.com/alexamoy/g4KIDpKNz.png?width=640&height=640&select=g4KIDpKNzpage0'},
  {character: 'Contessa', image: 'https://vectr.com/alexamoy/a3z26oDpXl.png?width=640&height=640&select=a3z26oDpXlpage0'}, {character: 'Contessa', image: 'https://vectr.com/alexamoy/a3z26oDpXl.png?width=640&height=640&select=a3z26oDpXlpage0'}, {character: 'Contessa', image: 'https://vectr.com/alexamoy/a3z26oDpXl.png?width=640&height=640&select=a3z26oDpXlpage0'},
  {character: 'Captain', image: 'https://vectr.com/alexamoy/iUsmXMVJA.png?width=640&height=640&select=iUsmXMVJApage0'}, {character: 'Captain', image: 'https://vectr.com/alexamoy/iUsmXMVJA.png?width=640&height=640&select=iUsmXMVJApage0'}, {character: 'Captain', image: 'https://vectr.com/alexamoy/iUsmXMVJA.png?width=640&height=640&select=iUsmXMVJApage0'},
  {character: 'Ambassador', image: 'https://vectr.com/alexamoy/g5UO1k3wGF.png?width=640&height=640&select=g5UO1k3wGFpage0'}, {character: 'Ambassador', image: 'https://vectr.com/alexamoy/g5UO1k3wGF.png?width=640&height=640&select=g5UO1k3wGFpage0'}, {character: 'Ambassador', image: 'https://vectr.com/alexamoy/g5UO1k3wGF.png?width=640&height=640&select=g5UO1k3wGFpage0'}
];

export default court;
